### ISSUE TITLE
USER STORY: Hiding the polls by the Administrator. 

### ISSUE THREAD

**Issue by Carlitos000** [Carlitos000/My-First-Agile-Project#7]
**In order** to automatically hide the poll **as an administrator, I can** pick the expiry date while publishing the pol
## Acceptance criteria:
- The pool should disappear at 11:59 PM on the target date.
- The pool's real state should be reserved on the home page, and a message that says  "Stay tuned, a new pool is coming soon" should appear if no other poll is active.
- The administrator's expiry date should be at least 3 days after the current date.

## Tasks:

- [ ] Update the admin module view: the poll design (HTML and CSS) to include the date picker.
- [ ] Update the website view: show "Stay tuned, a new poll is coming soon"
- [ ] Create a Javascript function to validate the expiry date at least after 3 days.
- [ ] Create a job to check expired polls every day at 11:59 PM and hide them.
- [ ] Update the controller function 
- [ ] update unit test scripts.
- [ ] Test the functionality.
